version: "3.7"
services:
  server:
    image: node:11-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - 9000:9000
    depends_on:
      - mongo
    networks:
      - webappnetwork
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
